# Generated by Django 4.0.6 on 2022-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('user_name', models.TextField(verbose_name='Имя автора')),
                ('user_link', models.URLField(verbose_name='Ссылка на автора')),
                ('r_date', models.PositiveIntegerField(verbose_name='Дата публикации')),
            ],
        ),
    ]
