# Generated by Django 4.0.6 on 2022-07-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparcer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
