# Generated by Django 4.1.6 on 2023-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcer', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='r_date',
            field=models.TextField(verbose_name='Дата публикации'),
        ),
    ]
